/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mobil;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Rifaldy
 */
public class beliMobil extends javax.swing.JFrame {
    
    String[] toyota = {"toyota camry","toyota avanza","toyota altis"};
    String[] volkswagen = {"volkswagen atlas","volkswagen golfs","volkswagen polo"};
    String[] ford = {"ford mustang","ford fusion","ford bronco"};
    int[][] harga = {{150000000,200000000,220000000},
                     {200000000,250000000,280000000},
                     {300000000,400000000,450000000}
    };
    String sql = "select * from mobil";
    
    
    ArrayList<Integer> seri = new ArrayList();
    int pilih;
    String code = "mobilku111";
    
    private void restart(){
        txtNama.setText(null);
        txtVoucher.setText(null);
        txtHarga.setText(null);
        cbMobil.setEnabled(false);
        cbMerk.setSelectedIndex(0);
        showData();
    }
    private void setMerk(int selected){
        pilih = selected -1;
        if (selected == 1){
            for(int i=0; i <= toyota.length-1;i++){
                cbMobil.addItem(toyota[i]);
            }
        }else if(selected == 2){
            for(int i=0; i <= volkswagen.length-1;i++){
                cbMobil.addItem(volkswagen[i]);
            }
                    
        }else if(selected == 3){
            for(int i=0; i <= ford.length-1;i++){
                cbMobil.addItem(ford[i]);
            }
            
        }
        
    }
    
    private void showData(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No");
        model.addColumn("Customer");
        model.addColumn("Mobil");
        model.addColumn("Seri");
        model.addColumn("Harga");
        model.addColumn("Status");
        
        try{
            int no = 1;
            String sql = "select * from mobil";
            java.sql.Connection con = (Connection)db.configDB();
            java.sql.Statement st = con.createStatement();
            java.sql.ResultSet res= st.executeQuery(sql);
            
            while(res.next()){
                model.addRow(new Object[]{no++,res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6)});
            }
            tables.setModel(model);
        }catch (SQLException e){
            System.out.println(e.getMessage());
        }
    }

    /**
     * Creates new form beliMobil
     */
    public beliMobil() {
        initComponents();
        showData();
        seri.add(0);
        seri.add(10);
        seri.add(5);
        seri.add(20);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        cbMerk = new javax.swing.JComboBox<>();
        cbMobil = new javax.swing.JComboBox<>();
        cbSeri = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtVoucher = new javax.swing.JTextField();
        btnBuat = new javax.swing.JButton();
        btnKirim = new javax.swing.JButton();
        btnTolak = new javax.swing.JButton();
        btnHarga = new javax.swing.JButton();
        txtHarga = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tables = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Aplikasi Pembelian Mobil");

        jLabel2.setText("Nama Cutomer :");

        jLabel3.setText("Merk Mobil :");

        jLabel4.setText("Pilih Mobil :");

        jLabel5.setText("Pilih Seri :");

        cbMerk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "pilih", "TOYOTA", "VOLKSWAGEN", "FORD" }));
        cbMerk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMerkActionPerformed(evt);
            }
        });

        cbMobil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "pilih" }));
        cbMobil.setEnabled(false);

        cbSeri.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "normal", "sport", "special", "deluxe" }));

        jLabel6.setText("Masukan Voucher :");

        btnBuat.setText("Buat pesanan");
        btnBuat.setEnabled(false);
        btnBuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuatActionPerformed(evt);
            }
        });

        btnKirim.setText("kirim");
        btnKirim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKirimActionPerformed(evt);
            }
        });

        btnTolak.setText("tolak");
        btnTolak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTolakActionPerformed(evt);
            }
        });

        btnHarga.setText("cek Harga");
        btnHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHargaActionPerformed(evt);
            }
        });

        txtHarga.setEditable(false);

        tables.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tables);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(btnHarga)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBuat)
                                .addGap(18, 18, 18)
                                .addComponent(btnKirim)
                                .addGap(18, 18, 18)
                                .addComponent(btnTolak)
                                .addGap(0, 166, Short.MAX_VALUE))
                            .addComponent(txtHarga, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNama)
                                    .addComponent(cbMerk, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbMobil, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbSeri, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtVoucher, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addGap(79, 79, 79))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbMerk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbMobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbSeri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuat)
                    .addComponent(btnKirim)
                    .addComponent(btnTolak)
                    .addComponent(btnHarga))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbMerkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMerkActionPerformed
        // TODO add your handling code here:
        int param = cbMerk.getSelectedIndex();
        cbMobil.removeAllItems();
        cbMobil.setEnabled(true);
        
        if (param != 0 ){
            setMerk(param);
        }
        
    }//GEN-LAST:event_cbMerkActionPerformed

    private void btnHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHargaActionPerformed
        // TODO add your handling code here:
         if(!txtNama.getText().equals("")){
            if(txtVoucher.getText().equals(code)){
                txtHarga.setText(String.valueOf((harga[pilih][cbMobil.getSelectedIndex()]+ harga[pilih][cbMobil.getSelectedIndex()]/100 * seri.get(cbSeri.getSelectedIndex()))/100*80));
            }else{
                txtHarga.setText(String.valueOf((harga[pilih][cbMobil.getSelectedIndex()]+ harga[pilih][cbMobil.getSelectedIndex()]/100 * seri.get(cbSeri.getSelectedIndex()))));
            }
            btnBuat.setEnabled(true);
            
        }else{
            showMessageDialog(null,"nama harus diisi");
        }
    }//GEN-LAST:event_btnHargaActionPerformed

    private void btnBuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuatActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "INSERT INTO mobil (customer,mobil,seri,harga,status) VALUES ('"+txtNama.getText()+ "','" + String.valueOf(cbMobil.getSelectedItem()) + "','" + cbSeri.getSelectedItem() + "'," + txtHarga.getText()  + ",'" + "proses" +"')";
            java.sql.Connection con = (Connection)db.configDB();
            java.sql.PreparedStatement ps = con.prepareStatement(sql);
            ps.execute();
            showMessageDialog(null,"berhasil memasukan data");
            restart();
            
        }catch(SQLException e){
            showMessageDialog(null,"gagal memasukan data");
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnBuatActionPerformed

    private void btnKirimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKirimActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "UPDATE mobil SET status ='dikirim' WHERE id="+(tables.getSelectedRow()+1);
            java.sql.Connection con = (Connection)db.configDB();
            java.sql.PreparedStatement ps = con.prepareStatement(sql);
            ps.execute();
            showMessageDialog(null,"berhasil mengubah data");
            restart();
            
        }catch(SQLException e){
            showMessageDialog(null,"gagal mengubah data");
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnKirimActionPerformed

    private void btnTolakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTolakActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "UPDATE mobil SET status ='ditolak' WHERE id="+(tables.getSelectedRow()+1);
            java.sql.Connection con = (Connection)db.configDB();
            java.sql.PreparedStatement ps = con.prepareStatement(sql);
            ps.execute();
            showMessageDialog(null,"berhasil mengubah data");
            restart();
            
        }catch(SQLException e){
            showMessageDialog(null,"gagal mengubah data");
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnTolakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(beliMobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(beliMobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(beliMobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(beliMobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new beliMobil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuat;
    private javax.swing.JButton btnHarga;
    private javax.swing.JButton btnKirim;
    private javax.swing.JButton btnTolak;
    private javax.swing.JComboBox<String> cbMerk;
    private javax.swing.JComboBox<String> cbMobil;
    private javax.swing.JComboBox<String> cbSeri;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tables;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtVoucher;
    // End of variables declaration//GEN-END:variables
}
